[package]
name = "cybar"
version = "0.1.0"
authors = ["Cyryl PÅ‚otnicki <cyplo@cyplo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
